namespace WineApp.DefaultValues
{
    public static class GrapeNameDefaults
    {
        public static List<String> GrapeNames
        {
            get
            {
                return new List<String>()
                {
                    "Aglianico",
                    "Albana",
                    "Albariño / Alvarinho",
                    "Aleatico",
                    "Alfrocheiro",
                    "Alicante Bouschet",
                    "Aligoté",
                    "Altesse",
                    "Alvarelhão",
                    "Antão Vaz",
                    "Aragonês / Aragonez",
                    "Arinto",
                    "Arneis",
                    "Assyrtico / Assyrtiko",
                    "Auxerrois",
                    "Avesso",
                    "Baco Noir",
                    "Baga",
                    "Barbera",
                    "Bical",
                    "Black Muscat",
                    "Blanc du Bois",
                    "Blaufränkisch",
                    "Bobal",
                    "Bonarda",
                    "Bordeaux-style Red Blend",
                    "Bordeaux-style White Blend",
                    "Brachetto",
                    "Braucol",
                    "Bual",
                    "Cabernet Franc",
                    "Cabernet Sauvignon",
                    "Cannonau",
                    "Carignan / Carignano",
                    "Carmenère",
                    "Carricante",
                    "Casavecchia",
                    "Castelão",
                    "Catarratto",
                    "Cencibel",
                    "Cerceal",
                    "Chambourcin",
                    "Champagne Blend",
                    "Charbono",
                    "Chardonnay",
                    "Chasselas",
                    "Chenin Blanc",
                    "Ciliegiolo",
                    "Cinsault",
                    "Clairette",
                    "Claret",
                    "Coda di Volpe",
                    "Colombard",
                    "Cortese",
                    "Corvina",
                    "Counoise",
                    "Dolcetto",
                    "Dornfelder",
                    "Duras",
                    "Durif",
                    "Encruzado",
                    "Falanghina",
                    "Fer Servadou",
                    "Fernão Pires",
                    "Feteasca Neagra",
                    "Fiano",
                    "Frappato",
                    "Friulano",
                    "Fumé Blanc",
                    "Furmint",
                    "Gaglioppo",
                    "Gamay",
                    "Garganega",
                    "Gewürztraminer",
                    "Glera (Prosecco)",
                    "Godello",
                    "Graciano",
                    "Grauburgunder",
                    "Grecanico",
                    "Grechetto",
                    "Greco / Greco Bianco",
                    "Grenache Blanc / Garnacha Blanca",
                    "Grenache-Syrah-Mourvèdre (G-S-M)",
                    "Grenache / Garnacha",
                    "Grillo",
                    "Gros Manseng",
                    "Grüner Veltliner",
                    "Hárslevelű",
                    "Hondarrabi Zuri",
                    "Inzolia / Insolia",
                    "Jacquère",
                    "Jaen",
                    "Kalecik Karasi",
                    "Kékfrankos",
                    "Kerner",
                    "Lagrein",
                    "Lambrusco",
                    "Lemberger",
                    "Loin de l'Oeil",
                    "Loureiro",
                    "Macabeo",
                    "Madeira Blend",
                    "Magliocco",
                    "Malagousia",
                    "Malbec",
                    "Malvasia",
                    "Mantonico",
                    "Manzoni",
                    "Marsanne",
                    "Marzemino",
                    "Mataro",
                    "Maturana",
                    "Mauzac",
                    "Mavrodaphne",
                    "Mavrud",
                    "Melon",
                    "Mencía",
                    "Meritage",
                    "Merlot",
                    "Mission",
                    "Molinara",
                    "Monastrell",
                    "Mondeuse",
                    "Monica",
                    "Montepulciano",
                    "Morillon",
                    "Moscadello",
                    "Moscatel",
                    "Moscatel Roxo",
                    "Moschofilero",
                    "Mourvèdre",
                    "Mtsvane",
                    "Müller-Thurgau",
                    "Muscadelle / Muscadel",
                    "Muscat / Moscato",
                    "Narince",
                    "Nascetta",
                    "Nebbiolo",
                    "Negrette",
                    "Negroamaro",
                    "Nerello Cappuccio",
                    "Nerello Mascalese",
                    "Nero d'Avola",
                    "Nero di Troia",
                    "Neuburger",
                    "Norton",
                    "Nosiola",
                    "Nuragus",
                    "Öküzgözü",
                    "Orange Muscat",
                    "Pallagrello",
                    "Palomino",
                    "Pansa Blanca",
                    "Passerina",
                    "Pecorino",
                    "Pedro Ximénez",
                    "Perricone",
                    "Petit Manseng",
                    "Petit Verdot",
                    "Petite Sirah",
                    "Picolit",
                    "Picpoul",
                    "Piedirosso",
                    "Pignoletto",
                    "Pinot Blanc / Pinot Bianco",
                    "Pinot Grigio / Pinot Gris",
                    "Pinot Meunier",
                    "Pinot Noir / Pinot Nero",
                    "Pinotage",
                    "Plavac Mali",
                    "Port",
                    "Posip",
                    "Prié Blanc",
                    "Prieto Picudo",
                    "Primitivo",
                    "Prugnolo Gentile",
                    "Raboso",
                    "Red Blend",
                    "Refosco",
                    "Rhône-Style Red Blend",
                    "Rhône-Style White Blend",
                    "Ribolla Gialla",
                    "Rieslaner",
                    "Riesling",
                    "Rivaner",
                    "Rkatsiteli",
                    "Robola",
                    "Roditis",
                    "Rolle",
                    "Rosé",
                    "Roter Veltliner",
                    "Rotgipfler",
                    "Roussanne",
                    "Ruché",
                    "Sagrantino",
                    "Sämling",
                    "Sangiovese",
                    "Saperavi",
                    "Sauvignon Blanc",
                    "Sauvignon Gris",
                    "Savagnin",
                    "Savatiano",
                    "Scheurebe",
                    "Schiava",
                    "Sémillon",
                    "Seyval Blanc",
                    "Sherry",
                    "Siria",
                    "Sousão",
                    "Sparkling Blend",
                    "Spätburgunder",
                    "St. Laurent",
                    "Susumaniello",
                    "Sylvaner / Silvaner",
                    "Symphony",
                    "Syrah / Shiraz",
                    "Tannat",
                    "Tempranillo",
                    "Tempranillo Blanco",
                    "Teran",
                    "Teroldego",
                    "Tinta de Toro",
                    "Tinta Fina / Tinto Fino",
                    "Tinta Roriz",
                    "Tinto del Pais",
                    "Tokaji / Tokay",
                    "Torrontés",
                    "Touriga Franca",
                    "Touriga Nacional",
                    "Traminer",
                    "Traminette",
                    "Trebbiano",
                    "Trepat",
                    "Trincadeira",
                    "Trousseau",
                    "Turbiana",
                    "Uva di Troia",
                    "Valdiguié",
                    "Verdeca",
                    "Verdejo",
                    "Verdelho",
                    "Verdicchio",
                    "Verduzzo Friulano / Verduzzo",
                    "Vermentino",
                    "Vernaccia",
                    "Vidal Blanc",
                    "Vignoles",
                    "Vilana",
                    "Viognier",
                    "Viura",
                    "Vranec",
                    "Weissburgunder",
                    "Welschriesling",
                    "White Blend",
                    "Xarel-lo",
                    "Xinomavro",
                    "Zibibbo",
                    "Zierfandler",
                    "Zinfandel",
                    "Zweigelt"
                };
            }
        }
    }
}

    