namespace WineApp.SoilComposition
{
    public static class SoilDefaults
    {
        public enum SoilTypes
        {
            Albariza,
            Alluvium,
            Basalt,
            Boulbènes,
            Brickearth,
            Calcareous,
            Carbonaceous,
            Chalk,
            Clay,
            Dolomite,
            Flint,
            Galestro,
            Granite,
            Gravel,
            Greywacke,
            Gypsum,
            Hardpan,
            Keuper,
            Kimmeridgian,
            Lignite,
            Limestone,
            Llicorella,
            Loam,
            Loess,
            Marl,
            Mica,
            Muschelkalk,
            Perlite,
            Quartz,
            Sand,
            Schist,
            Shale,
            Siliceous,
            Silt,
            Silex,
            Slate,
            TerraRossa,
            Tufa,
            Ultisol,
            Volcanic
        }
    }
}

